-- ---------------------------------------------------------------------------
-- JNCTF 初始表结构
--
-- 这份脚本由 JPA 实体生成后导出，之后新增字段请追加 V2、V3…… 迁移文件，
-- 不要改动本文件（Flyway 会校验校验和）。
-- ---------------------------------------------------------------------------

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Homebrew)
-- Dumped by pg_dump version 16.15 (Homebrew)




--
-- Name: announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    content text NOT NULL,
    created_by bigint,
    level character varying(16) NOT NULL,
    pinned boolean NOT NULL,
    published_at timestamp(6) with time zone NOT NULL,
    title character varying(200) NOT NULL,
    visible boolean NOT NULL
);


--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    last_used_at timestamp(6) with time zone,
    name character varying(64) NOT NULL,
    prefix character varying(16),
    revoked boolean NOT NULL,
    scopes character varying(255),
    token_hash character varying(128) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: api_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id bigint NOT NULL,
    content_type character varying(128),
    created_at timestamp(6) with time zone NOT NULL,
    filename character varying(255) NOT NULL,
    path character varying(512) NOT NULL,
    scope character varying(32),
    sha256 character varying(64),
    size bigint NOT NULL,
    url character varying(512) NOT NULL,
    user_id bigint
);


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(64) NOT NULL,
    actor_id bigint,
    actor_name character varying(64),
    created_at timestamp(6) with time zone NOT NULL,
    detail character varying(1000),
    ip character varying(64),
    target_id character varying(255),
    target_type character varying(32)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_attacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_attacks (
    id bigint NOT NULL,
    attacker_delta integer NOT NULL,
    attacker_team_id bigint NOT NULL,
    attacker_user_id bigint,
    awx_service_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    flag character varying(512) NOT NULL,
    round_id bigint NOT NULL,
    victim_delta integer NOT NULL,
    victim_target_id bigint NOT NULL,
    victim_team_id bigint NOT NULL
);


--
-- Name: awx_attacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_attacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_attacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_checks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_checks (
    id bigint NOT NULL,
    awx_service_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delta integer NOT NULL,
    duration_ms integer,
    message character varying(500),
    passed boolean NOT NULL,
    round_id bigint NOT NULL,
    team_id bigint NOT NULL
);


--
-- Name: awx_checks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_checks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_checks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_flags (
    id bigint NOT NULL,
    captured_count integer NOT NULL,
    competition_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expired boolean NOT NULL,
    flag character varying(512) NOT NULL,
    round_id bigint NOT NULL,
    target_id bigint NOT NULL,
    team_id bigint NOT NULL
);


--
-- Name: awx_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_rounds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_rounds (
    id bigint NOT NULL,
    competition_id bigint NOT NULL,
    end_at timestamp(6) with time zone NOT NULL,
    round_no integer NOT NULL,
    settled boolean NOT NULL,
    start_at timestamp(6) with time zone NOT NULL,
    state character varying(16) NOT NULL,
    CONSTRAINT awx_rounds_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'FINISHED'::character varying, 'SETTLED'::character varying])::text[])))
);


--
-- Name: awx_rounds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_rounds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_rounds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_services; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_services (
    id bigint NOT NULL,
    base_score integer NOT NULL,
    challenge_id bigint,
    check_path character varying(255),
    checker_script text,
    competition_id bigint NOT NULL,
    cpu_limit character varying(16),
    description text,
    docker_image character varying(255) NOT NULL,
    flag_env character varying(64),
    flag_file character varying(255),
    flag_template character varying(255) NOT NULL,
    internal_port integer NOT NULL,
    memory_limit_mb integer NOT NULL,
    name character varying(120) NOT NULL,
    protocol character varying(16) NOT NULL,
    reset_command character varying(512),
    sort_order integer NOT NULL
);


--
-- Name: awx_services_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: awx_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.awx_targets (
    id bigint NOT NULL,
    alive boolean NOT NULL,
    awx_service_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    container_id character varying(128),
    created_at timestamp(6) with time zone NOT NULL,
    current_flag character varying(512),
    error_message character varying(500),
    fail_streak integer NOT NULL,
    host character varying(128),
    port integer,
    status character varying(16) NOT NULL,
    team_id bigint NOT NULL,
    CONSTRAINT awx_targets_status_check CHECK (((status)::text = ANY ((ARRAY['CREATING'::character varying, 'RUNNING'::character varying, 'STOPPED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: awx_targets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.awx_targets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.awx_targets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    color character varying(16),
    description character varying(255),
    icon character varying(32),
    name character varying(48) NOT NULL,
    slug character varying(48) NOT NULL,
    sort_order integer NOT NULL,
    visible boolean NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenge_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenge_files (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    downloads integer NOT NULL,
    filename character varying(255) NOT NULL,
    sha256 character varying(64),
    size bigint NOT NULL,
    url character varying(512) NOT NULL
);


--
-- Name: challenge_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenge_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenge_flags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenge_flags (
    id bigint NOT NULL,
    case_sensitive boolean NOT NULL,
    challenge_id bigint NOT NULL,
    flag character varying(512) NOT NULL,
    type character varying(16) NOT NULL,
    CONSTRAINT challenge_flags_type_check CHECK (((type)::text = ANY ((ARRAY['STATIC'::character varying, 'REGEX'::character varying, 'DYNAMIC'::character varying])::text[])))
);


--
-- Name: challenge_flags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenge_flags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_flags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenge_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenge_instances (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    container_id character varying(128),
    created_at timestamp(6) with time zone NOT NULL,
    error_message character varying(500),
    expires_at timestamp(6) with time zone,
    host character varying(128),
    instance_flag character varying(512),
    port integer,
    status character varying(16) NOT NULL,
    team_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT challenge_instances_status_check CHECK (((status)::text = ANY ((ARRAY['CREATING'::character varying, 'RUNNING'::character varying, 'STOPPED'::character varying, 'EXPIRED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: challenge_instances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenge_instances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenge_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenge_tags (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: challenge_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenge_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenge_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenges (
    id bigint NOT NULL,
    allow_download boolean NOT NULL,
    allow_writeup boolean NOT NULL,
    attempt_count integer NOT NULL,
    author_id bigint,
    category_id bigint,
    connection_info text,
    connection_type character varying(16),
    container_port integer,
    cpu_limit character varying(16),
    created_at timestamp(6) with time zone NOT NULL,
    decay integer NOT NULL,
    description text,
    difficulty character varying(16) NOT NULL,
    docker_image character varying(255),
    hint_preview text,
    instance_ttl_seconds integer NOT NULL,
    max_attempts integer NOT NULL,
    memory_limit_mb integer NOT NULL,
    min_score integer NOT NULL,
    requires_container boolean NOT NULL,
    score integer NOT NULL,
    scoring_type character varying(16) NOT NULL,
    solve_count integer NOT NULL,
    sort_order integer NOT NULL,
    state character varying(16) NOT NULL,
    title character varying(160) NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT challenges_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['BEGINNER'::character varying, 'EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying, 'INSANE'::character varying])::text[]))),
    CONSTRAINT challenges_scoring_type_check CHECK (((scoring_type)::text = ANY ((ARRAY['STATIC'::character varying, 'DYNAMIC'::character varying])::text[]))),
    CONSTRAINT challenges_state_check CHECK (((state)::text = ANY ((ARRAY['VISIBLE'::character varying, 'HIDDEN'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: challenges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competition_announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competition_announcements (
    id bigint NOT NULL,
    competition_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint,
    title character varying(200) NOT NULL
);


--
-- Name: competition_announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competition_announcements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competition_announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competition_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competition_challenges (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    custom_score integer,
    sort_order integer NOT NULL
);


--
-- Name: competition_challenges_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competition_challenges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competition_challenges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competition_participants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competition_participants (
    id bigint NOT NULL,
    banned boolean NOT NULL,
    competition_id bigint NOT NULL,
    last_solve_at timestamp(6) with time zone,
    registered_at timestamp(6) with time zone NOT NULL,
    score integer NOT NULL,
    status character varying(16) NOT NULL,
    team_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT competition_participants_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: competition_participants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competition_participants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competition_participants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: competitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.competitions (
    id bigint NOT NULL,
    awd_attack_score integer NOT NULL,
    awd_defense_penalty integer NOT NULL,
    awd_round_seconds integer NOT NULL,
    banner character varying(512),
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint,
    description text,
    end_at timestamp(6) with time zone NOT NULL,
    freeze_at timestamp(6) with time zone,
    hide_challenges boolean NOT NULL,
    hide_scoreboard boolean NOT NULL,
    join_password character varying(64),
    max_participants integer NOT NULL,
    max_team_size integer NOT NULL,
    min_team_size integer NOT NULL,
    name character varying(160) NOT NULL,
    need_approval boolean NOT NULL,
    practice_after boolean NOT NULL,
    published boolean NOT NULL,
    rules text,
    slug character varying(16) NOT NULL,
    start_at timestamp(6) with time zone NOT NULL,
    state character varying(16) NOT NULL,
    subtitle character varying(255),
    team_mode character varying(16) NOT NULL,
    type character varying(16) NOT NULL,
    CONSTRAINT competitions_state_check CHECK (((state)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'RUNNING'::character varying, 'FROZEN'::character varying, 'ENDED'::character varying])::text[]))),
    CONSTRAINT competitions_team_mode_check CHECK (((team_mode)::text = ANY ((ARRAY['SOLO'::character varying, 'TEAM'::character varying, 'BOTH'::character varying])::text[]))),
    CONSTRAINT competitions_type_check CHECK (((type)::text = ANY ((ARRAY['JEOPARDY'::character varying, 'AWD'::character varying, 'MIXED'::character varying])::text[])))
);


--
-- Name: competitions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.competitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.competitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hint_unlocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hint_unlocks (
    id bigint NOT NULL,
    cost integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    hint_id bigint NOT NULL,
    team_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: hint_unlocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hint_unlocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hint_unlocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hints (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    content text NOT NULL,
    cost integer NOT NULL,
    deduct_from_challenge boolean NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: hints_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    content character varying(1000),
    created_at timestamp(6) with time zone NOT NULL,
    link character varying(255),
    is_read boolean NOT NULL,
    title character varying(200) NOT NULL,
    type character varying(32) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: point_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.point_logs (
    id bigint NOT NULL,
    balance integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    delta integer NOT NULL,
    reason character varying(120) NOT NULL,
    ref_id bigint,
    ref_type character varying(32),
    user_id bigint NOT NULL
);


--
-- Name: point_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.point_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.point_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key character varying(64) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    value text
);


--
-- Name: solves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solves (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    competition_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    first_blood boolean NOT NULL,
    score integer NOT NULL,
    second_blood boolean NOT NULL,
    solve_seconds bigint,
    team_id bigint,
    third_blood boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: solves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submissions (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    competition_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    flag character varying(512) NOT NULL,
    ip character varying(64),
    score integer NOT NULL,
    status character varying(16) NOT NULL,
    team_id bigint,
    user_agent character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT submissions_status_check CHECK (((status)::text = ANY ((ARRAY['CORRECT'::character varying, 'WRONG'::character varying, 'DUPLICATE'::character varying, 'RATE_LIMITED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    color character varying(16),
    name character varying(48) NOT NULL,
    usage_count integer NOT NULL
);


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_invites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_invites (
    id bigint NOT NULL,
    code character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by bigint NOT NULL,
    expires_at timestamp(6) with time zone,
    target_user_id bigint,
    team_id bigint NOT NULL,
    used_at timestamp(6) with time zone,
    used_by bigint
);


--
-- Name: team_invites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_invites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_invites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_members (
    id bigint NOT NULL,
    captain boolean NOT NULL,
    joined_at timestamp(6) with time zone NOT NULL,
    team_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: team_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    affiliation character varying(32),
    avatar character varying(512),
    banned boolean NOT NULL,
    captain_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(1000),
    hidden boolean NOT NULL,
    invite_code character varying(32),
    locked boolean NOT NULL,
    name character varying(48) NOT NULL,
    open_join boolean NOT NULL,
    score integer NOT NULL,
    website character varying(128)
);


--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ticket_messages (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    internal boolean NOT NULL,
    ticket_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: ticket_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ticket_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    assignee_id bigint,
    category character varying(32) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_reply_at timestamp(6) with time zone,
    priority character varying(16) NOT NULL,
    ref_id bigint,
    ref_type character varying(32),
    status character varying(16) NOT NULL,
    subject character varying(200) NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'PENDING'::character varying, 'RESOLVED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar character varying(512),
    ban_reason character varying(255),
    banned boolean NOT NULL,
    bio character varying(512),
    country character varying(64),
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(48),
    email character varying(128),
    email_verified boolean NOT NULL,
    hidden boolean NOT NULL,
    last_login_at timestamp(6) with time zone,
    last_login_ip character varying(64),
    locale character varying(8),
    newsletter boolean NOT NULL,
    organization character varying(32),
    password_hash character varying(255) NOT NULL,
    role character varying(16) NOT NULL,
    score integer NOT NULL,
    status character varying(16) NOT NULL,
    totp_enabled boolean NOT NULL,
    totp_secret character varying(64),
    updated_at timestamp(6) with time zone,
    username character varying(32) NOT NULL,
    website character varying(128),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PENDING'::character varying, 'BANNED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: writeups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.writeups (
    id bigint NOT NULL,
    challenge_id bigint NOT NULL,
    content text,
    created_at timestamp(6) with time zone NOT NULL,
    likes integer NOT NULL,
    reject_reason character varying(255),
    state character varying(16) NOT NULL,
    title character varying(200) NOT NULL,
    url character varying(512),
    user_id bigint NOT NULL,
    views integer NOT NULL,
    CONSTRAINT writeups_state_check CHECK (((state)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: writeups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.writeups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.writeups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);


--
-- Name: api_tokens api_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: awx_attacks awx_attacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_attacks
    ADD CONSTRAINT awx_attacks_pkey PRIMARY KEY (id);


--
-- Name: awx_checks awx_checks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_checks
    ADD CONSTRAINT awx_checks_pkey PRIMARY KEY (id);


--
-- Name: awx_flags awx_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_flags
    ADD CONSTRAINT awx_flags_pkey PRIMARY KEY (id);


--
-- Name: awx_rounds awx_rounds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_rounds
    ADD CONSTRAINT awx_rounds_pkey PRIMARY KEY (id);


--
-- Name: awx_services awx_services_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_services
    ADD CONSTRAINT awx_services_pkey PRIMARY KEY (id);


--
-- Name: awx_targets awx_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_targets
    ADD CONSTRAINT awx_targets_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: challenge_files challenge_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_files
    ADD CONSTRAINT challenge_files_pkey PRIMARY KEY (id);


--
-- Name: challenge_flags challenge_flags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_flags
    ADD CONSTRAINT challenge_flags_pkey PRIMARY KEY (id);


--
-- Name: challenge_instances challenge_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_instances
    ADD CONSTRAINT challenge_instances_pkey PRIMARY KEY (id);


--
-- Name: challenge_tags challenge_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_tags
    ADD CONSTRAINT challenge_tags_pkey PRIMARY KEY (id);


--
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (id);


--
-- Name: competition_announcements competition_announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competition_announcements
    ADD CONSTRAINT competition_announcements_pkey PRIMARY KEY (id);


--
-- Name: competition_challenges competition_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competition_challenges
    ADD CONSTRAINT competition_challenges_pkey PRIMARY KEY (id);


--
-- Name: competition_participants competition_participants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competition_participants
    ADD CONSTRAINT competition_participants_pkey PRIMARY KEY (id);


--
-- Name: competitions competitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitions
    ADD CONSTRAINT competitions_pkey PRIMARY KEY (id);


--
-- Name: hint_unlocks hint_unlocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hint_unlocks
    ADD CONSTRAINT hint_unlocks_pkey PRIMARY KEY (id);


--
-- Name: hints hints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hints
    ADD CONSTRAINT hints_pkey PRIMARY KEY (id);


--
-- Name: teams idx_teams_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT idx_teams_name UNIQUE (name);


--
-- Name: users idx_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_users_email UNIQUE (email);


--
-- Name: users idx_users_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_users_username UNIQUE (username);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: point_logs point_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point_logs
    ADD CONSTRAINT point_logs_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- Name: solves solves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solves
    ADD CONSTRAINT solves_pkey PRIMARY KEY (id);


--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: team_invites team_invites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_invites
    ADD CONSTRAINT team_invites_pkey PRIMARY KEY (id);


--
-- Name: team_members team_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT team_members_pkey PRIMARY KEY (id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: ticket_messages ticket_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT ticket_messages_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: awx_flags uk3d65cde795ejxy7dofg4u92am; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_flags
    ADD CONSTRAINT uk3d65cde795ejxy7dofg4u92am UNIQUE (flag);


--
-- Name: hint_unlocks uk6rh4e8n1ly3h27cakldj95ks6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hint_unlocks
    ADD CONSTRAINT uk6rh4e8n1ly3h27cakldj95ks6 UNIQUE (hint_id, user_id);


--
-- Name: competitions uk73cj8lrc01envytglt810q8y6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competitions
    ADD CONSTRAINT uk73cj8lrc01envytglt810q8y6 UNIQUE (slug);


--
-- Name: awx_rounds uk8shj4swni4e8e4un5q22u8ap6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_rounds
    ADD CONSTRAINT uk8shj4swni4e8e4un5q22u8ap6 UNIQUE (competition_id, round_no);


--
-- Name: api_tokens uk995ojedj5cc9b9ascbimawhnc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT uk995ojedj5cc9b9ascbimawhnc UNIQUE (token_hash);


--
-- Name: teams uk9in08syd61oyydey3f63ai6x9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT uk9in08syd61oyydey3f63ai6x9 UNIQUE (invite_code);


--
-- Name: competition_participants uk_comp_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competition_participants
    ADD CONSTRAINT uk_comp_user UNIQUE (competition_id, user_id);


--
-- Name: solves uk_solve_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solves
    ADD CONSTRAINT uk_solve_user UNIQUE (user_id, challenge_id, competition_id);


--
-- Name: challenge_tags ukbu23m32wjb31du34q3xpfunyy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_tags
    ADD CONSTRAINT ukbu23m32wjb31du34q3xpfunyy UNIQUE (challenge_id, tag_id);


--
-- Name: competition_challenges ukfy4978pw6raqjj2uchud2p38j; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.competition_challenges
    ADD CONSTRAINT ukfy4978pw6raqjj2uchud2p38j UNIQUE (competition_id, challenge_id);


--
-- Name: team_invites ukifyh4ssx3rqskr8nb55ih2s7r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_invites
    ADD CONSTRAINT ukifyh4ssx3rqskr8nb55ih2s7r UNIQUE (code);


--
-- Name: categories ukoul14ho7bctbefv8jywp5v3i2; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug);


--
-- Name: awx_targets ukqe4kftw6upktjufvkae2hnyqn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.awx_targets
    ADD CONSTRAINT ukqe4kftw6upktjufvkae2hnyqn UNIQUE (awx_service_id, team_id);


--
-- Name: team_members uks8nuwsa7nvebc246ed822w68x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_members
    ADD CONSTRAINT uks8nuwsa7nvebc246ed822w68x UNIQUE (team_id, user_id);


--
-- Name: tags ukt48xdq560gs3gap9g7jg36kgc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukt48xdq560gs3gap9g7jg36kgc UNIQUE (name);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: writeups writeups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.writeups
    ADD CONSTRAINT writeups_pkey PRIMARY KEY (id);


--
-- Name: idx_api_tokens_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_tokens_hash ON public.api_tokens USING btree (token_hash);


--
-- Name: idx_audit_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_created ON public.audit_logs USING btree (id DESC);


--
-- Name: idx_awx_attacks_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_awx_attacks_round ON public.awx_attacks USING btree (round_id);


--
-- Name: idx_awx_checks_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_awx_checks_round ON public.awx_checks USING btree (round_id, team_id);


--
-- Name: idx_awx_flags_round; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_awx_flags_round ON public.awx_flags USING btree (round_id);


--
-- Name: idx_awx_flags_value; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_awx_flags_value ON public.awx_flags USING btree (flag);


--
-- Name: idx_challenges_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_challenges_category ON public.challenges USING btree (category_id);


--
-- Name: idx_challenges_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_challenges_state ON public.challenges USING btree (state);


--
-- Name: idx_competitions_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_competitions_time ON public.competitions USING btree (start_at, end_at);


--
-- Name: idx_instances_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instances_status ON public.challenge_instances USING btree (status);


--
-- Name: idx_instances_user_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_instances_user_challenge ON public.challenge_instances USING btree (user_id, challenge_id);


--
-- Name: idx_notifications_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id, is_read, id);


--
-- Name: idx_point_logs_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_point_logs_user ON public.point_logs USING btree (user_id, id);


--
-- Name: idx_solves_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solves_challenge ON public.solves USING btree (challenge_id);


--
-- Name: idx_solves_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solves_user ON public.solves USING btree (user_id);


--
-- Name: idx_submissions_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_challenge ON public.submissions USING btree (challenge_id, id);


--
-- Name: idx_submissions_competition; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_competition ON public.submissions USING btree (competition_id, id);


--
-- Name: idx_submissions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_user ON public.submissions USING btree (user_id, id);


--
-- Name: idx_teams_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_teams_score ON public.teams USING btree (score);


--
-- Name: idx_ticket_messages; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticket_messages ON public.ticket_messages USING btree (ticket_id, id);


--
-- Name: idx_tickets_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tickets_status ON public.tickets USING btree (status, id);


--
-- Name: idx_users_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_score ON public.users USING btree (score);


--
-- Name: idx_writeups_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_writeups_challenge ON public.writeups USING btree (challenge_id);


--
-- PostgreSQL database dump complete
--
